"""
SpectaSyncAI: Incident RAG Agent — @03 @05 @12
Powered by: google-adk + Gemini 2.5 Pro + pgvector (AlloyDB)

Responsibility:
  Given a live crowd event profile (venue_type, density, failure_modes in play,
  vip_delay, rumor_detected, infra_status), performs semantic similarity search
  against the 12-incident global corpus to retrieve the most analogous historical
  events. Returns ranked similar incidents with their proven intervention strategies.

RAG Architecture:
  Encoding:    Feature vector of crowd event profile → cosine similarity search
  Retrieval:   Top-K (default 3) most similar incidents from INCIDENT_CORPUS
  Generation:  Gemini 2.5 Pro synthesizes a unified intervention strategy from
               retrieved incidents, adapted to the current venue's real-time state.

Production: Uses AlloyDB pgvector for embedding search.
Prototype:  Uses in-memory cosine similarity on float feature vectors.
"""
import json
import logging
import math
from google.adk.agents import LlmAgent
from google.adk.runners import InMemoryRunner
from google.adk.sessions import InMemorySessionService
from google.genai import types as genai_types

from .incident_corpus import INCIDENT_CORPUS, IncidentRecord

logger = logging.getLogger(__name__)

# Failure mode to integer encoding for feature vector
FAILURE_MODE_INDEX = {
    "EXOGENOUS_SURGE": 0,
    "TEMPORAL_DISRUPT": 1,
    "INFO_CASCADE": 2,
    "INFRA_FAILURE": 3,
    "EGRESS_FAILURE": 4,
    "NARROW_CORRIDOR": 5,
    "PANIC_TRIGGER": 6,
    "BRIDGE_BOTTLENECK": 7,
    "TICKETING_CHAOS": 8,
    "TEMPLE_SURGE": 9,
}

VENUE_TYPE_INDEX = {
    "outdoor_ground": 0, "stadium": 1, "street": 2,
    "bridge": 3, "corridor": 4, "temple": 5,
}

EVENT_TYPE_INDEX = {
    "political_rally": 0, "concert": 1, "sports": 2,
    "festival": 3, "religious": 4, "civic": 5,
}


def _vectorize_incident(record: IncidentRecord) -> list[float]:
    """Converts an IncidentRecord to a normalized feature vector for similarity search."""
    vec = [0.0] * (len(FAILURE_MODE_INDEX) + len(VENUE_TYPE_INDEX) + len(EVENT_TYPE_INDEX) + 5)

    # Failure mode flags (0-9)
    for fm in record.failure_modes:
        idx = FAILURE_MODE_INDEX.get(fm)
        if idx is not None:
            vec[idx] = 1.0

    # Venue type (10-15)
    vt_offset = len(FAILURE_MODE_INDEX)
    vt = VENUE_TYPE_INDEX.get(record.venue_type, 0)
    vec[vt_offset + vt] = 1.0

    # Event type (16-21)
    et_offset = vt_offset + len(VENUE_TYPE_INDEX)
    et = EVENT_TYPE_INDEX.get(record.event_type, 0)
    vec[et_offset + et] = 1.0

    # Scalar features (22-26)
    scalar_offset = et_offset + len(EVENT_TYPE_INDEX)
    capacity_ratio = min(1.0, record.estimated_attendance / max(1, record.venue_capacity) / 10.0)
    vec[scalar_offset] = capacity_ratio
    vec[scalar_offset + 1] = 1.0 if record.vip_delay_involved else 0.0
    vec[scalar_offset + 2] = 1.0 if record.infra_failure_involved else 0.0
    vec[scalar_offset + 3] = 1.0 if record.rumor_involved else 0.0
    vec[scalar_offset + 4] = min(1.0, record.deaths / 500.0)  # severity proxy

    return vec


def _cosine_similarity(v1: list[float], v2: list[float]) -> float:
    """Computes cosine similarity between two feature vectors."""
    dot = sum(a * b for a, b in zip(v1, v2))
    mag1 = math.sqrt(sum(a * a for a in v1))
    mag2 = math.sqrt(sum(b * b for b in v2))
    if mag1 == 0 or mag2 == 0:
        return 0.0
    return dot / (mag1 * mag2)


def search_similar_incidents(
    active_failure_modes: list[str],
    venue_type: str,
    event_type: str,
    capacity_ratio: float,
    vip_delay: bool = False,
    infra_failure: bool = False,
    rumor_detected: bool = False,
    top_k: int = 3,
) -> dict:
    """
    Semantic similarity search against the global incident corpus.
    Production: Queries AlloyDB pgvector with embedding generated by text-embedding-004.

    Args:
        active_failure_modes: Failure modes currently detected in the live event.
        venue_type: Current venue category.
        event_type: Type of event being monitored.
        capacity_ratio: Current estimated attendance / venue capacity.
        vip_delay: Whether a VIP/performer/political figure delay is active.
        infra_failure: Whether any infrastructure component has failed.
        rumor_detected: Whether a dangerous social rumor has been detected.
        top_k: Number of similar incidents to retrieve.

    Returns:
        dict: Top-K most similar incidents with similarity scores and lessons.
    """
    # Build query vector
    query_record = IncidentRecord(
        incident_id="LIVE_EVENT",
        year=2026,
        country_iso2="XX",
        event_type=event_type,
        estimated_attendance=int(capacity_ratio * 50_000),
        venue_capacity=50_000,
        deaths=0,
        injuries=0,
        failure_modes=active_failure_modes,
        primary_trigger="Live event — queried for similarities",
        key_precursor_signals=[],
        interventions_that_would_have_helped=[],
        time_of_day_category="during_event",
        venue_type=venue_type,
        vip_delay_involved=vip_delay,
        infra_failure_involved=infra_failure,
        rumor_involved=rumor_detected,
        lessons_learned=[],
    )
    query_vec = _vectorize_incident(query_record)

    # Score all corpus incidents
    scored = []
    for record in INCIDENT_CORPUS:
        corpus_vec = _vectorize_incident(record)
        sim = _cosine_similarity(query_vec, corpus_vec)
        scored.append((sim, record))

    scored.sort(key=lambda x: x[0], reverse=True)
    top_results = scored[:top_k]

    return {
        "query_failure_modes": active_failure_modes,
        "query_venue_type": venue_type,
        "query_event_type": event_type,
        "top_k": top_k,
        "similar_incidents": [
            {
                "incident_id": rec.incident_id,
                "similarity_score": round(sim, 3),
                "year": rec.year,
                "country": rec.country_iso2,
                "event_type": rec.event_type,
                "deaths": rec.deaths,
                "failure_modes": rec.failure_modes,
                "primary_trigger": rec.primary_trigger,
                "proven_interventions": rec.interventions_that_would_have_helped,
                "lessons_learned": rec.lessons_learned,
            }
            for sim, rec in top_results
        ],
    }


def aggregate_intervention_strategies(incident_ids: list[str]) -> dict:
    """
    Aggregates and de-duplicates intervention strategies from a set of historical incidents.
    Used by the RAG Agent to synthesize a unified prevention plan.

    Args:
        incident_ids: List of incident IDs retrieved by similarity search.

    Returns:
        dict: Merged intervention strategies ranked by frequency/priority.
    """
    id_set = set(incident_ids)
    intervention_counter: dict[str, int] = {}
    all_lessons: list[str] = []

    for record in INCIDENT_CORPUS:
        if record.incident_id in id_set:
            for intervention in record.interventions_that_would_have_helped:
                intervention_counter[intervention] = intervention_counter.get(intervention, 0) + 1
            all_lessons.extend(record.lessons_learned)

    ranked_interventions = sorted(intervention_counter.items(), key=lambda x: x[1], reverse=True)

    return {
        "unified_interventions": [
            {"action": action, "referenced_by_n_incidents": count}
            for action, count in ranked_interventions
        ],
        "consolidated_lessons": list(set(all_lessons)),
        "incident_count": len(id_set),
    }


def build_incident_rag_agent() -> LlmAgent:
    """
    Constructs the Incident RAG Agent using Gemini 2.5 Pro.
    Retrieves analogous historical incidents and generates intervention strategies.

    Returns:
        LlmAgent: Configured incident RAG agent.
    """
    corpus_summary = (
        f"{len(INCIDENT_CORPUS)} incidents | "
        f"Span: 2010–2025 | "
        f"Countries: {len(set(r.country_iso2 for r in INCIDENT_CORPUS))} | "
        f"Total deaths: {sum(r.deaths for r in INCIDENT_CORPUS):,}"
    )

    return LlmAgent(
        model="gemini-2.5-pro-preview-03-25",
        name="incident_rag_agent",
        description=(
            "Performs RAG-based similarity search against a global crowd crush incident "
            "corpus to retrieve and apply learnings from analogous historical events."
        ),
        instruction=(
            f"You are SpectaSyncAI's Incident RAG Agent. You have access to a curated "
            f"global crowd incident corpus: [{corpus_summary}].\n\n"
            "Protocol:\n"
            "1. Call search_similar_incidents() with the current event's profile.\n"
            "2. Call aggregate_intervention_strategies() with the retrieved incident IDs.\n"
            "3. Synthesize a JSON response containing:\n"
            "   - matched_incidents: list of incident IDs with similarity scores\n"
            "   - combined_risk_level: NORMAL|MODERATE|HIGH|CRITICAL|CATASTROPHIC\n"
            "   - priority_interventions: top 5 actions ranked by historical evidence\n"
            "   - historical_lessons: 3 key learnings most relevant to current scenario\n"
            "   - prevention_confidence_pct: 0-100 confidence this scenario is preventable\n"
            "Do NOT reference any persons, brands, venues, or political entities by name. "
            "Use only incident IDs (e.g., INC-2025-IND-01) for references."
        ),
        tools=[search_similar_incidents, aggregate_intervention_strategies],
    )


async def run_incident_rag_query(
    active_failure_modes: list[str],
    venue_type: str,
    event_type: str,
    capacity_ratio: float,
    vip_delay: bool = False,
    infra_failure: bool = False,
    rumor_detected: bool = False,
) -> dict:
    """
    Runs the Incident RAG Agent for a live crowd scenario.

    Returns:
        dict: Similar incidents, aggregated interventions, and prevention strategy.
    """
    agent = build_incident_rag_agent()
    session_service = InMemorySessionService()
    runner = InMemoryRunner(agent=agent, session_service=session_service)

    session = await session_service.create_session(
        app_name="spectasync_rag", user_id="system"
    )

    prompt = (
        "INCIDENT RAG QUERY — Live crowd scenario:\n"
        f"  Active failure modes: {active_failure_modes}\n"
        f"  Venue type: {venue_type}\n"
        f"  Event type: {event_type}\n"
        f"  Capacity ratio: {capacity_ratio:.2f}x\n"
        f"  VIP delay active: {vip_delay}\n"
        f"  Infrastructure failure: {infra_failure}\n"
        f"  Rumor detected: {rumor_detected}\n"
        "Search for the 3 most similar historical incidents and synthesize "
        "a prevention strategy based on those evidence-based interventions."
    )

    result_text = ""
    async for event in runner.run_async(
        user_id="system",
        session_id=session.id,
        new_message=genai_types.Content(
            role="user",
            parts=[genai_types.Part(text=prompt)],
        ),
    ):
        if event.is_final_response() and event.content:
            for part in event.content.parts:
                if part.text:
                    result_text += part.text

    logger.info(f"[IncidentRAGAgent] RAG query complete: {result_text[:200]}")

    try:
        clean = result_text.strip().lstrip("```json").rstrip("```").strip()
        return json.loads(clean)
    except json.JSONDecodeError:
        similar = search_similar_incidents(
            active_failure_modes, venue_type, event_type, capacity_ratio,
            vip_delay, infra_failure, rumor_detected
        )
        ids = [i["incident_id"] for i in similar["similar_incidents"]]
        strategies = aggregate_intervention_strategies(ids)

        return {
            "matched_incidents": [
                {"incident_id": i["incident_id"], "similarity_score": i["similarity_score"]}
                for i in similar["similar_incidents"]
            ],
            "combined_risk_level": "CRITICAL" if capacity_ratio > 2.0 else "HIGH" if capacity_ratio > 1.5 else "MODERATE",
            "priority_interventions": [
                s["action"] for s in strategies["unified_interventions"][:5]
            ],
            "historical_lessons": strategies["consolidated_lessons"][:3],
            "prevention_confidence_pct": min(90, int((1 - max(0, capacity_ratio - 1) / 5) * 90)),
            "corpus_searched": len(INCIDENT_CORPUS),
        }
